id: P18C2B04B
initial_creation_type: ocr
source_metadata:
  volumes:
    61adea571916459f91d079708f27fc90:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: སློབ་དཔོན་ཀཱ་མ་ལ་ཤཱི་ལའི་སྨོན་ལམ་མུ་གཉིས་མ།
      total_pages: 1880
      volume_number: 116
